### ISSUE TITLE
Duplicate Flymake diagnostics when using pyls

### ISSUE THREAD

**Issue by federicotdn** [joaotavora/eglot#223]
I've noticed some Flymake diagnostics get duplicated when using Eglot with `pyls`, after shutting down Eglot and starting it again. The steps to reproduce this issue are:
1) Create a new directory with a virtual environment `env` and install `pyls`:
```bash
$ mkdir eglot-test
$ cd eglot-test
$ python3 -m venv env
$ source env/bin/activate
$ pip install python-language-server[all]
```

2) Then, on Emacs:
<kbd>C-x C-f</kbd> to a new file inside `eglot-test`, say `hello.py`, and insert the following contents:
```python
import random
print("hello")
```

3) Install `pyvenv` and use <kbd>M-x</kbd>`pyvenv-activate` to activate `env`.
4) Enable Eglot <kbd>M-x</kbd>`eglot`.
Now, at line 1, the following diagnostic should have appeared: `pyflakes: 'random' imported but unused`.
5) Shutdown Eglot with <kbd>M-x</kbd>`eglot-shutdown` and enable it again.
6) Now there will be *two* diagnostics at line 1, with the same contents.

This was tested on Emacs 26.1, Eglot version `20190205.2149`.

**Comment by federicotdn** [comment]
Also: after step 6, if the file is modified and saved, the diagnostic on line 1 will be duplicated again. I've noticed that the buffer-local variable `flymake--backend-state` continues to grow as these diagnostics are added:

```elisp
(flymake--backend-state . #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data
					 (eglot-flymake-backend #s(flymake--backend-state backend-token84 t nil
											  (#s(flymake--diag #<buffer hello.py> 1 12 eglot-warning "pyflakes: 'math' imported but unused" eglot-flymake-backend
													    ((eglot-lsp-diag :source "pyflakes" :range
															     (:start
															      (:line 0 :character 0)
															      :end
															      (:line 0 :character 12))
															     :message "'math' imported but unused" :severity 2))
													    nil #<overlay from 1 to 12 in hello.py>)
											     #s(flymake--diag #<buffer hello.py> 1 12 eglot-warning "pyflakes: 'math' imported but unused" eglot-flymake-backend
													      ((eglot-lsp-diag :source "pyflakes" :range
															       (:start
																(:line 0 :character 0)
																:end
																(:line 0 :character 12))
															       :message "'math' imported but unused" :severity 2))
													      nil #<overlay from 1 to 12 in hello.py>)
											     #s(flymake--diag #<buffer hello.py> 1 12 eglot-warning "pyflakes: 'math' imported but unused" eglot-flymake-backend
													      ((eglot-lsp-diag :source "pyflakes" :range
															       (:start
																(:line 0 :character 0)
																:end
																(:line 0 :character 12))
															       :message "'math' imported but unused" :severity 2))
													      nil #<overlay from 1 to 12 in hello.py>)
											     #s(flymake--diag #<buffer hello.py> 1 12 eglot-warning "pyflakes: 'math' imported but unused" eglot-flymake-backend
													      ((eglot-lsp-diag :source "pyflakes" :range
															       (:start
																(:line 0 :character 0)
																:end
																(:line 0 :character 12))
															       :message "'math' imported but unused" :severity 2))
													      nil #<overlay from 1 to 12 in hello.py>)
											     #s(flymake--diag #<buffer hello.py> 1 12 eglot-warning "pyflakes: 'math' imported but unused" eglot-flymake-backend
													      ((eglot-lsp-diag :source "pyflakes" :range
															       (:start
																(:line 0 :character 0)
																:end
																(:line 0 :character 12))
															       :message "'math' imported but unused" :severity 2))
													      nil #<overlay from 1 to 12 in hello.py>)))
								flymake-proc-legacy-flymake #s(flymake--backend-state nil t
														      (error "Can’t find a suitable init function")
														      nil))))

```

(using `import math` as the first line)

**Comment by joaotavora** [comment]
Your recipe is very detailed on the Python side, but you forgot to state how you are invoking Emacs.  In particular, I need to know exactly how you are installing Eglot and its dependencies, `jsonrpc.el` and `flymake.el`.

Can you try the whole thing again, but starting with `Emacs -Q`?

**Comment by federicotdn** [comment]
No problem:
I actually tried this using `env HOME=/another/directory emacs` which allowed me to install packages on a separate `.emacs.d/elpa` dir. The new HOME did not have a `.emacs.d/init.el` file so it was equivalent to doing `emacs -q`.  After Emacs started up, I evaluated the following:
```elisp
(require 'package)
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("marmalade" . "http://marmalade-repo.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(package-initialize)
```

Then, I installed pyvenv and Eglot with:
<kbd>M-x</kbd>`package-refresh-contents`<kbd>[RET]</kbd>
<kbd>M-x</kbd>`package-install`<kbd>[RET]</kbd>`pyvenv`<kbd>[RET]</kbd>
<kbd>M-x</kbd>`package-install`<kbd>[RET]</kbd>`eglot`<kbd>[RET]</kbd>

`jsonrpc.el` was installed as a dependency of Eglot by `package.el`, and I used the version of Flymake bundled with Emacs 26.1.

**Comment by joaotavora** [comment]
> And I used the version of Flymake bundled with Emacs 26.1.

This cannot be. You must ensure you are also using flymake.el as provided by ELPA. It must be 1.0.3.  Can you check with `M-x find-library RET flymake`?

**Comment by federicotdn** [comment]
Just checked with `find-library`, the installed version is `1.0.3` (I was wrong about it being the version bundled with Emacs).

**Comment by joaotavora** [comment]
I was so lost on the fine details that I forgot to read the most important part of your report, which is it only happens when you reconnect Eglot.  This is a Flymake bug that I fixed in 1.0.4 which will be available soon from GNU ELPA (or if you decide to build your emacs from master).

**Comment by joaotavora** [comment]
If you do decide to build from master, this is the Emacs commit that has the fix:
```
ommit b78363eb0f51126b2c22d26ea1b91f6e4569e167 (HEAD -> master, origin/master, origin/HEAD)
Author: João Távora <joaotavora@gmail.com>
Date:   Sun Feb 10 12:05:52 2019 +0000

    Cleanup stale diagnostics on Flymake restart
    
    Not doing so would cause duplicate diagnostics.  See
    https://github.com/joaotavora/eglot/issues/223 for an example.
    
    * lisp/progmodes/flymake.el (Version): 1.0.4
    (flymake-mode): Cleanup overlays before starting Flymake.
```

**Comment by joaotavora** [comment]
Actually, better reopen this until I can push the commit that fixes this, which updates the `Package-requires` of Flymake to version 1.4.

**Comment by federicotdn** [comment]
I tested it again on Emacs master branch and it now working correctly. Thanks!

**Comment by federicotdn** [comment]
It seems like the second problem I described (on my second comment) still persists. The short description of the problem is: when using Eglot + pyls, editing a buffer seems to create duplicate Flymake diagnostics. The steps to reproduce are:

1. On Emacs master branch (`24695e8977`), with no `init.el`, evaluate the following:
```elisp
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
	("marmalade" . "http://marmalade-repo.org/packages/")
	("melpa" . "https://melpa.org/packages/")))
```
2. Do <kbd>M-x</kbd>`package-refresh-contents`, and then <kbd>M-x</kbd>`package-install` with `pyvenv` and `eglot`. This will install Eglot version `20190205.2149`. JsonRPC version will be `1.0.7` and Flymake's `1.0.4`.

3. Create a new directory with a Python 3 virtual environment `env` and install `pyls`.

4. Back on Emacs, <kbd>C-x C-f</kbd> to a new file (`hello.py`) and insert the following:
```python
import math
print('hello world')
```
5. Activate `env` using `pyvenv-activate` and then launch Eglot. There should be one Flymake diagnostic at line 1 (import `math` is unused).
6. Now, evaluate the following: `(progn (goto-char 1) (goto-char (line-end-position)) (newline))`.
7. An extra, duplicated diagnostic should have been added to line 1. Repeating step 6 will add more diagnostics.

**Comment by joaotavora** [comment]
There is a separate bug in flymake.el.  It isn't hard, but is trickier than the previous one.

**Comment by federicotdn** [comment]
Would you prefer if I reported an Emacs bug instead? The problem is that I'm not sure how to reproduce the problem without using Eglot.

**Comment by joaotavora** [comment]
> Would you prefer if I reported an Emacs bug instead? The problem is that I'm not sure how to reproduce the problem without using Eglot.

No need, fixed this one too.
```
commit 459869a528ff02787255391ab90f68195c27b807
Author: João Távora <joaotavora@gmail.com>
Date:   Sun Feb 10 21:38:46 2019 +0000

    Properly remove stale Flymake diagnostics on :region reports
    
    Among other bugs fixed, modifying a list structure while iterating it
    is a no-no.  This would again cause duplicate diagnostics.  See
    https://github.com/joaotavora/eglot/issues/223 for an example.
    
    * lisp/progmodes/flymake.el (Version): Bump to 1.0.5
    (flymake--handle-report): Use cl-loop.
```

**Comment by joaotavora** [comment]
Some time tomorrow 1.0.5 should be up in elpa.gnu.org.  I'll update Eglot to require that version then.

**Comment by federicotdn** [comment]
Thanks! Tried again on Emacs master branch, and it works correctly.
